### ISSUE TITLE
there is support for 'locale' from moment?

### ISSUE THREAD

**Issue by spiral2k** [remcoder/chronos#13]
im trying to use this option from the moment API and its not working :cry:

**Comment by remcoder** [comment]
Chronos shouldn't interfere with how moment works. If it doesn't work as you expect I suggest:
- try moment w/o Chronos to see if the problem persists
- lookup the moment docs to check you're doing everything correctly
- especially the way your locales should be installed and initialized
- check which moment version you're using with meteor and possibly try another
- if the problem is indeed caused by Chronos please post the exact code so I can reproduce the issue.

I'll close the issue for now. Feel free to re-open if it's a Chronos bug.

HTH
