### ISSUE TITLE
"Can't set timers inside simulations" error

### ISSUE THREAD

**Issue by H1D** [remcoder/chronos#5]
I can't set any liveUpdate timer inside helpers =(
Always getting this error

```
Exception in template helper: Error: Can't set timers inside simulations
    at withoutInvocation (http://localhost:3000/packages/meteor.js?e53378596562e8922a6369c955bab1e047fa866b:434:13)
    at bindAndCatch (http://localhost:3000/packages/meteor.js?e53378596562e8922a6369c955bab1e047fa866b:442:33)
    at Object._.extend.setInterval (http://localhost:3000/packages/meteor.js?e53378596562e8922a6369c955bab1e047fa866b:469:24)
    at Timer.start (http://localhost:3000/packages/remcoder_chronos.js?4c1cdaa85e6dd33110a630278df769a417ebcf63:46:24)
    at Object.liveUpdate (http://localhost:3000/packages/remcoder_chronos.js?4c1cdaa85e6dd33110a630278df769a417ebcf63:64:18)
    at Object.Template.guestRow.helpers.total_bill (http://localhost:3000/client/views/counter/guest-row.coffee.js?3cad82c01820f7dcb6bd214c5565e85716efc3bd:15:13)
    at bindDataContext (http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:2786:16)
    at Blaze._wrapCatchingExceptions (http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:1607:16)
    at http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:2834:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:3382:12)
```

I've tried to reproduce this error with http://meteorpad.com/ but I can't =(

**Comment by remcoder** [comment]
Could you post a code snippet?

**Comment by H1D** [comment]
Got it! 
Press "MOAR" button here – http://app-gw3n5agg.meteorpad.com/
Source code here – http://meteorpad.com/pad/hEMxTmbjAmHHHmLJF/Copy%20of%20Chronos.Timer

**Comment by remcoder** [comment]
Thanks! meteorpad seems to be unresponsive now and then (it could be b/c I'm tethering) so I haven't found anything conclusive yet but I did notice that your meteorpad is running a rather old (and buggy!) version (0.1.3) of Chronos. Could you check you're using the latest version (0.2.2) in your app?

**Comment by H1D** [comment]
yes. I am using 0.2.2

**Comment by H1D** [comment]
BTW here is 0.2.2 on meteorpad
http://app-setuz5mk.meteorpad.com/
http://meteorpad.com/pad/hEMxTmbjAmHHHmLJF/Copy%20of%20Chronos.Timer
Just open console and click button:
![chronos](https://cloud.githubusercontent.com/assets/697625/6942694/ef9e9914-d891-11e4-860c-1cd67a0574ea.gif)

**Comment by remcoder** [comment]
Ah, so it does display a date sometimes, but at other times it throws an error. Weird. 

Not sure when I'll get around to fixing this. It's kinda elusive and I'm currently on a vacation.. Any suggestions at this point would also be really appreciated ;-)

**Comment by H1D** [comment]
It works for existing items. But fails for items created during current sessions

**Comment by Multiply** [comment]
I am hitting this problem as well. When creating the timer, just check for `!this.isSimulation`

**Comment by H1D** [comment]
@Multiply and what to do if `this.isSimulation === true` ?

**Comment by remcoder** [comment]
hmm, the solution isn't that simple I'm afraid. To check wether you're in a simulation you can do this: 

```
if (Package.ddp) {
  var _CurrentInvocation = Package.ddp.DDP._CurrentInvocation;
  if (_CurrentInvocation.get() && _CurrentInvocation.get().isSimulation)
    // do something about it
}
```

(taken from https://github.com/meteor/meteor/blob/master/packages/meteor/timers.js#L2-5)

..but, if you skip creating the timer when the simulation is run, the helper wil not be called again until the document changes. The only way I know to defer execution to a later time (so as to push it outside the simulation) is.. a `setTimeout` :-/

Actually, there is a corresponding issue in the Meteor repo, which is still unresolved too: https://github.com/meteor/meteor/issues/2691

I could use `window.setInterval` (possibly together with `Meteor.bindEnvironment`) which doesn't check if it's running inside a simulation but he underlying problem is that whatever is done inside a simulation should be reversible b/c the method might fail on the server. So if we create a timer and the method fails, there is still a timer left running. 

Any thoughts?

**Comment by remcoder** [comment]
Fixed it by using `window.setInterval` together with `Meteor.bindEnvironment`. Although I'm circumventing Meteor's mechanism trying to prevent doing side-effects inside a simulation it shouldn't be a problem. The timer is actually correctly disposed of too so no memory leaks or dangling timers ;-)

**Comment by H1D** [comment]
Cool! Thx
